Add golden tests
projectsyn/component-csi-driver-smb pull request #23
Opened 2022-06-22 21:00 UTC by anothertobi

## Checklist

- [x] PR contains a single logical change (to build a better changelog).
- [x] Categorize the PR by setting a good title and adding one of the labels:
      `bug`, `enhancement`, `documentation`, `change`, `breaking`, `dependency`
      as they show up in the changelog.

2022-06-22 21:01 UTC, anothertobi commented
Didn't update the `Makefile` on purpose, since this is managed by ModuleSync.

2022-06-23 06:39 UTC, simu requested changes

2022-06-23 06:39 UTC, simu commented on .sync.yml
> +  githubUrl: https://github.com/projectsyn/component-csi-driver-smb
This is not needed at all

```suggestion
```

2022-06-23 06:39 UTC, simu commented on .sync.yml
> +  feature_goUnitTests: false
This is the default, so it doesn't need to be specified.
```suggestion
```

2022-06-23 06:47 UTC, simu approved these changes
eclint will not complain about errors in the golden test outputs once you get the updated config from modulesync IIRC

2022-06-23 06:51 UTC, merged

2022-06-23 06:58 UTC, anothertobi commented
Related ModuleSync PR: https://github.com/projectsyn/component-csi-driver-smb/pull/25